-- MySQL Script generated by MySQL Workbench
-- Wed May 12 10:49:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema classicAuto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `classicAuto` ;

-- -----------------------------------------------------
-- Schema classicAuto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classicAuto` DEFAULT CHARACTER SET utf8 ;
USE `classicAuto` ;

-- -----------------------------------------------------
-- Table `classicAuto`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classicAuto`.`users` ;

CREATE TABLE IF NOT EXISTS `classicAuto`.`users` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phonenumber` INT(16) NULL,
  `email` VARCHAR(100) NOT NULL,
  `locality` VARCHAR(100) NOT NULL,
  `npa` INT NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueUser` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classicAuto`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classicAuto`.`cars` ;

CREATE TABLE IF NOT EXISTS `classicAuto`.`cars` (
  `id` INT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `image` VARCHAR(50) NOT NULL,
  `year` INT NOT NULL,
  `mileage` INT NOT NULL,
  `horsepower` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `gearbox` VARCHAR(45) NOT NULL,
  `fuel` VARCHAR(45) NOT NULL,
  `weight` INT NOT NULL,
  `drivingwheel` VARCHAR(45) NOT NULL,
  `serialnumber` VARCHAR(50) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueCars` (`serialnumber` ASC) VISIBLE,
  INDEX `fk_cars_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_cars_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `classicAuto`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
