-- MySQL Script generated by MySQL Workbench
-- Wed Jun  2 11:00:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema classicAuto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `classicAuto` ;

-- -----------------------------------------------------
-- Schema classicAuto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `classicAuto` DEFAULT CHARACTER SET utf8 ;
USE `classicAuto` ;

-- -----------------------------------------------------
-- Table `classicAuto`.`sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classicAuto`.`sellers` ;

CREATE TABLE IF NOT EXISTS `classicAuto`.`sellers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `phonenumber` VARCHAR(10) NULL,
  `email` VARCHAR(319) NOT NULL,
  `locality` VARCHAR(30) NOT NULL,
  `npa` INT(4) NOT NULL,
  `street` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueUser` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `classicAuto`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `classicAuto`.`cars` ;

CREATE TABLE IF NOT EXISTS `classicAuto`.`cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(55) NOT NULL,
  `model` VARCHAR(55) NOT NULL,
  `image` VARCHAR(65) NOT NULL,
  `year` INT NOT NULL,
  `mileage` INT NOT NULL,
  `horsepower` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `gearbox` VARCHAR(15) NOT NULL,
  `fuel` VARCHAR(15) NOT NULL,
  `weight` INT NOT NULL,
  `drivingwheels` VARCHAR(15) NOT NULL,
  `chassisnumber` VARCHAR(17) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueCars` (`chassisnumber` ASC) VISIBLE,
  INDEX `fk_cars_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_cars_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `classicAuto`.`sellers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
